name: bump

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cni-plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - run: ./hack/bump/cni-plugins.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          push-to-fork: vexxhost-bot/ansible-collection-containers
          commit-message: "chore(deps): update cni-plugins"
          signoff: true
          branch: bump/cni-plugins
          delete-branch: true
          title: "chore(deps): update cni-plugins"
          body: |
            ## Automated `cni-plugins` update

            This PR updates the `cni-plugins` binaries to the latest versions.

  containerd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - run: ./hack/bump/containerd.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          push-to-fork: vexxhost-bot/ansible-collection-containers
          commit-message: "chore(deps): update containerd"
          signoff: true
          branch: bump/containerd
          delete-branch: true
          title: "chore(deps): update containerd"
          body: |
            ## Automated `containerd` update

            This PR updates the `containerd` binaries to the latest versions.

  cri-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - run: ./hack/bump/cri-tools.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          push-to-fork: vexxhost-bot/ansible-collection-containers
          commit-message: "chore(deps): update cri-tools"
          signoff: true
          branch: bump/cri-tools
          delete-branch: true
          title: "chore(deps): update cri-tools"
          body: |
            ## Automated `cri-tools` update

            This PR updates the `cri-tools` binaries to the latest versions.

  nerdctl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - run: ./hack/bump/nerdctl.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          push-to-fork: vexxhost-bot/ansible-collection-containers
          commit-message: "chore(deps): update nerdctl"
          signoff: true
          branch: bump/nerdctl
          delete-branch: true
          title: "chore(deps): update nerdctl"
          body: |
            ## Automated `nerdctl` update

            This PR updates the `nerdctl` binaries to the latest versions.

  runc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - run: ./hack/bump/runc.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          push-to-fork: vexxhost-bot/ansible-collection-containers
          commit-message: "chore(deps): update runc"
          signoff: true
          branch: bump/runc
          delete-branch: true
          title: "chore(deps): update runc"
          body: |
            ## Automated `runc` update

            This PR updates the `runc` binaries to the latest versions.
